---
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion "bash" > ./completions/esi.bash'
    - sh -c 'go run . completion "zsh" > ./completions/esi.zsh'
    - sh -c 'go run . completion "fish" > ./completions/esi.fish'
    - sh -c 'go run . man | gzip -c > ./manpages/esi.1.gz'

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    main: "."
    binary: esi
    ldflags:
      - -s
      - -w
      - -X github.com/jon4hz/esi/version.Version={{ .Version }}
      - -X github.com/jon4hz/esi/version.Commit={{ .Commit }}
      - -X github.com/jon4hz/esi/version.Date={{ .Date }}
      - -X github.com/jon4hz/esi/version.BuiltBy=gitlab-ci
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    rlcp: true
    name_template: "esi-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    builds:
      - default
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - manpages/
      - completions

checksum:
  name_template: "checksums.txt"

nfpms:
  - file_name_template: "esi-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    vendor: jon4hz
    maintainer: "jonah <me@jon4hz.io>"
    description: "inject secrets from TSS"
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: ./completions/esi.bash
        dst: /etc/bash_completion.d/esi
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./completions/esi.fish
        dst: /usr/share/fish/vendor_completions.d/esi.fish
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./completions/esi.zsh
        dst: /usr/share/zsh/site-functions/_esi
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: ./manpages/esi.1.gz
        dst: /usr/share/man/man1/esi.1.gz
        file_info:
          mode: 0644
          owner: root
          group: root

changelog:
  sort: asc
  use: gitlab
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^wip:"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependency updates"
      regexp: "^.*fix\\(deps\\):+.*$"
      order: 20
    - title: Others
      order: 999
